apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.ngrok.com
    chart: ngrok-operator
    targetRevision: 0.21.0
    helm:
      values: |
        credentials:
          secret:
            name: "ngrok-secret"
  destination:
    server: https://kubernetes.default.svc
    namespace: ngrok
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
